### PR TITLE
3: upgraded from POI 4.0 to 5.0. getCellTypeEnum was removed in 5.x. …

### LINKED ISSUE #3: Upgrade POI dependency from 4.0 to v.5.x
jxls-reader depends on an outdated version of POI 4.x and should be updated to 5.x.

### PR DESCRIPTION
**Pull request by samb0t**
…Usages were replaced with getCellType

Fixes https://github.com/jxlsteam/jxls-reader/issues/3

### CODE REVIEW

**Review by leonate — APPROVED** [review]

**Comment by samb0t** [comment]
Thank you for the quick approval. Is it possible this would make it into a release in the near future?

**Comment by leonate** [comment]
@samb0t , I hope to find some time to make a release in the next few weeks.

**Comment by samb0t** [comment]
Thanks again.

**Comment by sxjas** [comment]
Hello, can you please do a release? Thank you

**Pull request merged**
